api_platform:
    title: Woo balie API
    version: 0.1.0
    show_webby: false
    formats:
        json: ['application/json']
    error_formats:
        json: ['application/json']
    docs_formats:
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        collectDenormalizationErrors: true
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    exception_to_status:
        Doctrine\ORM\NoResultException: 404
    resource_class_directories:
      - '%kernel.project_dir%/src/Api'
    enable_entrypoint: false
    enable_swagger: false
    enable_swagger_ui: false
    enable_docs: false
    enable_re_doc: false

when@dev:
    api_platform:
        enable_entrypoint: true
        enable_swagger: true
        enable_swagger_ui: true
        enable_docs: true
        enable_re_doc: true
