parameters:
    audit_logger.psr_logger.encrypted: '%env(bool:AUDITLOG_PSR_ENCRYPTED)%'
    audit_logger.psr_logger.log_pii: '%env(bool:AUDITLOG_PSR_LOG_PII)%'
    audit_logger.file_logger.encrypted: '%env(bool:AUDITLOG_FILE_ENCRYPTED)%'
    audit_logger.file_logger.log_pii: '%env(bool:AUDITLOG_FILE_LOG_PII)%'
    audit_logger.file_logger.path: '%env(resolve:AUDITLOG_FILE_PATH)%'
    audit_logger.doctrine_logger.encrypted: '%env(bool:AUDITLOG_DOCTRINE_ENCRYPTED)%'
    audit_logger.doctrine_logger.log_pii: '%env(bool:AUDITLOG_DOCTRINE_LOG_PII)%'
    audit_logger.rabbitmq_logger.encrypted: '%env(bool:AUDITLOG_RABBITMQ_ENCRYPTED)%'
    audit_logger.rabbitmq_logger.log_pii: '%env(bool:AUDITLOG_RABBITMQ_LOG_PII)%'
    audit_logger.rabbitmq.routing_key: '%env(AUDITLOG_RABBITMQ_ROUTING_KEY)%'
    audit_logger.encryption.pub_key: '%env(AUDITLOG_ENCRYPTION_PUB_KEY)%'
    audit_logger.encryption.priv_key: '%env(AUDITLOG_ENCRYPTION_PRIV_KEY)%'

audit_logger:
    encryption:
        public_key: '%audit_logger.encryption.pub_key%'
        private_key: '%audit_logger.encryption.priv_key%'

    loggers:
        psr_logger:
            enabled: true
            encrypted: '%audit_logger.psr_logger.encrypted%'
            log_pii: '%audit_logger.psr_logger.log_pii%'
        doctrine_logger:
            enabled: true
            encrypted: '%audit_logger.doctrine_logger.encrypted%'
            log_pii: '%audit_logger.doctrine_logger.log_pii%'
        rabbitmq_logger:
            enabled: true
            encrypted: '%audit_logger.rabbitmq_logger.encrypted%'
            log_pii: '%audit_logger.rabbitmq_logger.log_pii%'
            routing_key: '%audit_logger.rabbitmq.routing_key%'
            producer_service: 'old_sound_rabbit_mq.audit_logger_producer'
            additional_events: [ ]
        file_logger:
            enabled: false
            encrypted: '%audit_logger.file_logger.encrypted%'
            log_pii: '%audit_logger.file_logger.log_pii%'
            path: '%audit_logger.file_logger.path%'

when@dev:
    audit_logger:
        loggers:
            rabbitmq_logger:
                enabled: false
            file_logger:
                enabled: true

when@test:
    audit_logger:
        loggers:
            rabbitmq_logger:
                enabled: false
