snc_redis:
    clients:
        ingest:
            type: predis
            alias: ingest
            dsn: '%redis.url%'
            options:
                parameters:
                    ssl_context: {
                        'verify_peer': true,
                        'allow_self_signed': false,
                        'verify_peer_name': true,
                        'cafile': '%redis.tls.cafile%',
                        'local_cert': '%redis.tls.local_cert%',
                        'local_pk': '%redis.tls.local_pk%'
                    }

        session:
            type: predis
            alias: session
            dsn: '%redis.url%'
            options:
                parameters:
                    ssl_context: {
                        'verify_peer': true,
                        'allow_self_signed': false,
                        'verify_peer_name': true,
                        'cafile': '%redis.tls.cafile%',
                        'local_cert': '%redis.tls.local_cert%',
                        'local_pk': '%redis.tls.local_pk%'
                    }
