snc_redis:
    clients:
        ingest:
            type: predis
            alias: ingest
            dsn: '%env(REDIS_URL)%'
            options:
                parameters:
                    ssl_context: {
                        'verify_peer': true,
                        'allow_self_signed': false,
                        'verify_peer_name': true,
                        'cafile': '%env(REDIS_TLS_CAFILE)%',
                        'local_cert': '%env(REDIS_TLS_LOCAL_CERT)%',
                        'local_pk': '%env(REDIS_TLS_LOCAL_PK)%'
                    }

        session:
            type: predis
            alias: session
            dsn: '%env(REDIS_URL)%'
            options:
                parameters:
                    ssl_context: {
                        'verify_peer': true,
                        'allow_self_signed': false,
                        'verify_peer_name': true,
                        'cafile': '%env(REDIS_TLS_CAFILE)%',
                        'local_cert': '%env(REDIS_TLS_LOCAL_CERT)%',
                        'local_pk': '%env(REDIS_TLS_LOCAL_PK)%'
                    }

        admin:
            type: predis
            alias: admin
            dsn: '%env(REDIS_URL)%'
            options:
                parameters:
                    ssl_context: {
                        'verify_peer': true,
                        'allow_self_signed': false,
                        'verify_peer_name': true,
                        'cafile': '%env(REDIS_TLS_CAFILE)%',
                        'local_cert': '%env(REDIS_TLS_LOCAL_CERT)%',
                        'local_pk': '%env(REDIS_TLS_LOCAL_PK)%'
                    }
