framework:
    default_locale: nl
    translator:
        default_path: '%kernel.project_dir%/tenants/%kernel.tenant_id%/translations'
        paths:
            - '%kernel.project_dir%/translations'
