when@dev:
    web_profiler:
        toolbar:
            enabled: '%enable_symfony_toolbar%'

    framework:
        profiler:
            collect: '%enable_symfony_toolbar%'

when@test:
    framework:
        profiler:
            collect: false
