version: '3'
services:
  tika:
    image: apache/tika:latest
    platform: linux/amd64
    labels:
       com.symfony.server.service-ignore: true
    ports:
      - target: 9998
        published: 9998
    networks:
      - woopie

  app:
    build: ./docker
    labels:
       com.symfony.server.service-ignore: true
    ports:
      - target: 80
        published: 8000
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/custom.d/php.ini
      - ~/.npmrc:/root/.npmrc
    networks:
      - woopie
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"

  elasticsearch:
    image: elasticsearch:8.2.2
    labels:
       com.symfony.server.service-ignore: true
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=/https:\/\/app.elasticvue.com/
#      - http.cors.allow-headers: X-Requested-With,Content-Type,Content-Length,Authorization
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - woopie

  redis:
    image: redis:5
    labels:
       com.symfony.server.service-ignore: true
    ports:
      - target: 6379
        published: 6379
    networks:
      - woopie

  rabbitmq:
    image: rabbitmq:3-management
    labels:
       com.symfony.server.service-ignore: true
    ports:
      - target: 5672
        published: 5672
      - target: 15672
        published: 15672
    networks:
      - woopie

  postgres:
    image: postgres:12.1
    labels:
      com.symfony.server.service-ignore: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - target: 5432
        published: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - woopie

volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local

networks:
  woopie:
    driver: bridge
