<?php

declare(strict_types=1);

namespace PublicationApi\Domain\OpenApi\Schema;

use ApiPlatform\OpenApi\Model\Operation;
use ApiPlatform\OpenApi\Model\Response;
use ArrayObject;
use PublicationApi\Domain\OpenApi\Schema\Component\OpenApiResponseComponentProvider;
use PublicationApi\Domain\OpenApi\Schema\Component\OpenApiSchemaComponentProvider;
use PublicationApi\Domain\OpenApi\Schema\Component\OperationResponseDefinition;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

use function in_array;
use function strtoupper;

final readonly class CommonResponses implements OpenApiSchemaComponentProvider, OpenApiResponseComponentProvider
{
    public function getSchemas(): array
    {
        return [
            'ProblemDetails' => [
                'type' => 'object',
                'description' => 'RFC 9457 Problem Details',
                'required' => ['type', 'title', 'status'],
                'properties' => [
                    'type' => [
                        'description' => 'A URI reference that identifies the problem type.',
                        'type' => 'string',
                        'format' => 'uri',
                        'readOnly' => true,
                    ],
                    'title' => [
                        'description' => 'A short, human-readable summary of the problem.',
                        'type' => 'string',
                        'readOnly' => true,
                    ],
                    'status' => [
                        'description' => 'The HTTP status code generated by the origin server for this occurrence of the problem.',
                        'type' => 'integer',
                        'readOnly' => true,
                    ],
                    'detail' => [
                        'description' => 'A human-readable explanation specific to this occurrence of the problem.',
                        'type' => 'string',
                        'readOnly' => true,
                    ],
                    'instance' => [
                        'description' => 'A URI reference that identifies the specific occurrence of the problem. It '
                            . 'may or may not yield further information if dereferenced.',
                        'type' => 'string',
                        'format' => 'uri',
                        'readOnly' => true,
                    ],
                ],
            ],
        ];
    }

    public function getResponses(): array
    {
        return [
            new OperationResponseDefinition(
                statusCode: (string) SymfonyResponse::HTTP_BAD_REQUEST, // 400
                response: new Response(
                    description: 'Bad request',
                    content: new ArrayObject([
                        'application/problem+json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/ProblemDetails',
                            ],
                        ],
                    ]),
                ),
            ),
            new OperationResponseDefinition(
                statusCode: (string) SymfonyResponse::HTTP_UNAUTHORIZED, // 401
                response: new Response(
                    description: 'Unauthorized',
                    content: new ArrayObject([
                        'application/problem+json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/ProblemDetails',
                            ],
                        ],
                    ]),
                ),
            ),
            new OperationResponseDefinition(
                statusCode: (string) SymfonyResponse::HTTP_FORBIDDEN, // 403
                response: new Response(
                    description: 'Forbidden',
                    content: new ArrayObject([
                        'application/problem+json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/ProblemDetails',
                            ],
                        ],
                    ]),
                ),
            ),
            new OperationResponseDefinition(
                statusCode: (string) SymfonyResponse::HTTP_NOT_FOUND, // 404
                response: new Response(
                    description: 'Not found',
                    content: new ArrayObject([
                        'application/problem+json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/ProblemDetails',
                            ],
                        ],
                    ]),
                ),
            ),
            new OperationResponseDefinition(
                statusCode: (string) SymfonyResponse::HTTP_METHOD_NOT_ALLOWED, // 405
                response: new Response(
                    description: 'Method not allowed',
                    content: new ArrayObject([
                        'application/problem+json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/ProblemDetails',
                            ],
                        ],
                    ]),
                ),
            ),
            new OperationResponseDefinition(
                statusCode: (string) SymfonyResponse::HTTP_UNPROCESSABLE_ENTITY, // 422
                response: new Response(
                    description: 'Validation failed',
                    content: new ArrayObject([
                        'application/problem+json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/ProblemDetails',
                            ],
                        ],
                    ]),
                ),
                when: static function (Operation $operation, string $path, string $httpMethod): bool {
                    return in_array(strtoupper($httpMethod), ['POST', 'PUT', 'PATCH'], true);
                },
            ),
            new OperationResponseDefinition(
                statusCode: (string) SymfonyResponse::HTTP_INTERNAL_SERVER_ERROR, // 500
                response: new Response(
                    description: 'Server error',
                    content: new ArrayObject([
                        'application/problem+json' => [
                            'schema' => [
                                '$ref' => '#/components/schemas/ProblemDetails',
                            ],
                        ],
                    ]),
                ),
            ),
        ];
    }
}
