<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250310105114 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE attachment ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE attachment ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE attachment ALTER formal_date TYPE DATE');
        $this->addSql('ALTER TABLE attachment ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE attachment ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE attachment ALTER withdraw_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN attachment.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN attachment.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN attachment.formal_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN attachment.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN attachment.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN attachment.withdraw_date IS \'\'');
        $this->addSql('ALTER TABLE audit_entry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE audit_entry ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN audit_entry.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN audit_entry.created_at IS \'\'');
        $this->addSql('ALTER TABLE batch_download ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE batch_download ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE batch_download ALTER expiration TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE batch_download ALTER inquiry_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN batch_download.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN batch_download.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN batch_download.expiration IS \'\'');
        $this->addSql('COMMENT ON COLUMN batch_download.inquiry_id IS \'\'');
        $this->addSql('ALTER TABLE department ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN department.id IS \'\'');
        $this->addSql('ALTER TABLE document ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document ALTER document_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document ALTER withdraw_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN document.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN document.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN document.document_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN document.withdraw_date IS \'\'');
        $this->addSql('ALTER TABLE document_dossier ALTER document_id TYPE UUID');
        $this->addSql('ALTER TABLE document_dossier ALTER woo_decision_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_dossier.document_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_dossier.woo_decision_id IS \'\'');
        $this->addSql('ALTER TABLE document_referrals ALTER document_id TYPE UUID');
        $this->addSql('ALTER TABLE document_referrals ALTER referred_document_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_referrals.document_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_referrals.referred_document_id IS \'\'');
        $this->addSql('ALTER TABLE document_file_set ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_set ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_set ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_set ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN document_file_set.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_set.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_set.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_set.updated_at IS \'\'');
        $this->addSql('ALTER TABLE document_file_update ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_update ALTER document_file_set_id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_update ALTER document_id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_update ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_update ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN document_file_update.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.document_file_set_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.document_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.updated_at IS \'\'');
        $this->addSql('ALTER TABLE document_file_upload ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_upload ALTER document_file_set_id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_upload ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_upload ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN document_file_upload.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_upload.document_file_set_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_upload.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_file_upload.updated_at IS \'\'');
        $this->addSql('ALTER TABLE document_prefix ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_prefix ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_prefix.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_prefix.organisation_id IS \'\'');
        $this->addSql('ALTER TABLE dossier ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE dossier ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE dossier ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE dossier ALTER date_from TYPE DATE');
        $this->addSql('ALTER TABLE dossier ALTER date_to TYPE DATE');
        $this->addSql('ALTER TABLE dossier ALTER publication_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE dossier ALTER preview_date TYPE DATE');
        $this->addSql('ALTER TABLE dossier ALTER decision_date TYPE DATE');
        $this->addSql('ALTER TABLE dossier ALTER organisation_id TYPE UUID');
        $this->addSql('ALTER TABLE dossier ALTER subject_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN dossier.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.date_from IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.date_to IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.publication_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.preview_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.decision_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.organisation_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier.subject_id IS \'\'');
        $this->addSql('ALTER TABLE dossier_department ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE dossier_department ALTER department_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN dossier_department.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN dossier_department.department_id IS \'\'');
        $this->addSql('ALTER TABLE encrypted_audit_entry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE encrypted_audit_entry ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN encrypted_audit_entry.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN encrypted_audit_entry.created_at IS \'\'');
        $this->addSql('ALTER TABLE history ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE history ALTER identifier TYPE UUID');
        $this->addSql('ALTER TABLE history ALTER created_dt TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN history.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN history.identifier IS \'\'');
        $this->addSql('COMMENT ON COLUMN history.created_dt IS \'\'');
        $this->addSql('ALTER TABLE inquiry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inquiry ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inquiry ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inquiry.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry.organisation_id IS \'\'');
        $this->addSql('ALTER TABLE inquiry_document ALTER inquiry_id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry_document ALTER document_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inquiry_document.inquiry_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry_document.document_id IS \'\'');
        $this->addSql('ALTER TABLE inquiry_dossier ALTER inquiry_id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry_dossier ALTER woo_decision_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inquiry_dossier.inquiry_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry_dossier.woo_decision_id IS \'\'');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER inquiry_id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.inquiry_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.updated_at IS \'\'');
        $this->addSql('ALTER TABLE inventory ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE inventory ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE inventory ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inventory ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN inventory.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN inventory.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN inventory.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN inventory.updated_at IS \'\'');
        $this->addSql('ALTER TABLE login_activity ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE login_activity ALTER account_id TYPE UUID');
        $this->addSql('ALTER TABLE login_activity ALTER login_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN login_activity.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN login_activity.account_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN login_activity.login_at IS \'\'');
        $this->addSql('ALTER TABLE main_document ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE main_document ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE main_document ALTER formal_date TYPE DATE');
        $this->addSql('ALTER TABLE main_document ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE main_document ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN main_document.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN main_document.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN main_document.formal_date IS \'\'');
        $this->addSql('COMMENT ON COLUMN main_document.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN main_document.updated_at IS \'\'');
        $this->addSql('ALTER TABLE organisation ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE organisation ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE organisation ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN organisation.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN organisation.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN organisation.updated_at IS \'\'');
        $this->addSql('ALTER TABLE organisation_department ALTER organisation_id TYPE UUID');
        $this->addSql('ALTER TABLE organisation_department ALTER department_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN organisation_department.organisation_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN organisation_department.department_id IS \'\'');
        $this->addSql('ALTER TABLE production_report ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE production_report ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE production_report ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN production_report.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN production_report.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN production_report.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN production_report.updated_at IS \'\'');
        $this->addSql('ALTER TABLE production_report_process_run ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE production_report_process_run ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE production_report_process_run ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report_process_run ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report_process_run ALTER ended_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.dossier_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.started_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.ended_at IS \'\'');
        $this->addSql('ALTER TABLE subject ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE subject ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN subject.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN subject.organisation_id IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "user" ALTER mfa_token TYPE text');
        $this->addSql('ALTER TABLE "user" ALTER mfa_recovery TYPE text');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".mfa_token IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".mfa_recovery IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".organisation_id IS \'\'');
        $this->addSql('ALTER TABLE woo_index_sitemap ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE woo_index_sitemap ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE woo_index_sitemap ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN woo_index_sitemap.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN woo_index_sitemap.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN woo_index_sitemap.updated_at IS \'\'');
        $this->addSql('ALTER TABLE worker_stats ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE worker_stats ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN worker_stats.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN worker_stats.created_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE document_dossier ALTER document_id TYPE UUID');
        $this->addSql('ALTER TABLE document_dossier ALTER woo_decision_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_dossier.document_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document_dossier.woo_decision_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE document_file_set ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_set ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_set ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_set ALTER dossier_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_file_set.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document_file_set.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document_file_set.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document_file_set.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE inquiry_document ALTER inquiry_id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry_document ALTER document_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inquiry_document.inquiry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN inquiry_document.document_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE attachment ALTER withdraw_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE attachment ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE attachment ALTER formal_date TYPE DATE');
        $this->addSql('ALTER TABLE attachment ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE attachment ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE attachment ALTER dossier_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN attachment.withdraw_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN attachment.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN attachment.formal_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN attachment.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN attachment.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN attachment.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE organisation_department ALTER organisation_id TYPE UUID');
        $this->addSql('ALTER TABLE organisation_department ALTER department_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN organisation_department.organisation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN organisation_department.department_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE worker_stats ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE worker_stats ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN worker_stats.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN worker_stats.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE subject ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE subject ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN subject.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subject.organisation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE encrypted_audit_entry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE encrypted_audit_entry ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN encrypted_audit_entry.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN encrypted_audit_entry.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE production_report_process_run ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE production_report_process_run ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report_process_run ALTER started_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report_process_run ALTER ended_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report_process_run ALTER dossier_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.started_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.ended_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN production_report_process_run.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE production_report ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE production_report ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE production_report ALTER dossier_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN production_report.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN production_report.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN production_report.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN production_report.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE audit_entry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE audit_entry ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN audit_entry.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_entry.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE department ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN department.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE login_activity ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE login_activity ALTER login_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE login_activity ALTER account_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN login_activity.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN login_activity.login_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN login_activity.account_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE history ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE history ALTER identifier TYPE UUID');
        $this->addSql('ALTER TABLE history ALTER created_dt TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN history.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN history.identifier IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN history.created_dt IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE dossier ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE dossier ALTER date_from TYPE DATE');
        $this->addSql('ALTER TABLE dossier ALTER date_to TYPE DATE');
        $this->addSql('ALTER TABLE dossier ALTER publication_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE dossier ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE dossier ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE dossier ALTER organisation_id TYPE UUID');
        $this->addSql('ALTER TABLE dossier ALTER subject_id TYPE UUID');
        $this->addSql('ALTER TABLE dossier ALTER preview_date TYPE DATE');
        $this->addSql('ALTER TABLE dossier ALTER decision_date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN dossier.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dossier.date_from IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dossier.date_to IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dossier.publication_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dossier.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dossier.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dossier.organisation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dossier.subject_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dossier.preview_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dossier.decision_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE dossier_department ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE dossier_department ALTER department_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN dossier_department.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dossier_department.department_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE inventory ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE inventory ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inventory ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inventory ALTER dossier_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inventory.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN inventory.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN inventory.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN inventory.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE main_document ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE main_document ALTER formal_date TYPE DATE');
        $this->addSql('ALTER TABLE main_document ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE main_document ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE main_document ALTER dossier_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN main_document.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN main_document.formal_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN main_document.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN main_document.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN main_document.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE document_referrals ALTER document_id TYPE UUID');
        $this->addSql('ALTER TABLE document_referrals ALTER referred_document_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_referrals.document_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document_referrals.referred_document_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE woo_index_sitemap ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE woo_index_sitemap ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE woo_index_sitemap ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN woo_index_sitemap.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN woo_index_sitemap.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN woo_index_sitemap.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inquiry_inventory ALTER inquiry_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN inquiry_inventory.inquiry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE inquiry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inquiry ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE inquiry ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inquiry.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN inquiry.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN inquiry.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN inquiry.organisation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE organisation ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE organisation ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE organisation ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN organisation.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN organisation.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN organisation.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE document_file_upload ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_upload ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_upload ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_upload ALTER document_file_set_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_file_upload.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document_file_upload.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document_file_upload.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document_file_upload.document_file_set_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE batch_download ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE batch_download ALTER expiration TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE batch_download ALTER dossier_id TYPE UUID');
        $this->addSql('ALTER TABLE batch_download ALTER inquiry_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN batch_download.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN batch_download.expiration IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN batch_download.dossier_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN batch_download.inquiry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE document ALTER document_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document ALTER withdraw_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN document.document_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document.withdraw_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE document_prefix ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_prefix ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_prefix.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document_prefix.organisation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE inquiry_dossier ALTER inquiry_id TYPE UUID');
        $this->addSql('ALTER TABLE inquiry_dossier ALTER woo_decision_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN inquiry_dossier.inquiry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN inquiry_dossier.woo_decision_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE "user" ALTER mfa_token TYPE TEXT');
        $this->addSql('ALTER TABLE "user" ALTER mfa_recovery TYPE TEXT');
        $this->addSql('ALTER TABLE "user" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE "user" ALTER organisation_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN "user".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "user".mfa_token IS \'(DC2Type:encrypted_string)\'');
        $this->addSql('COMMENT ON COLUMN "user".mfa_recovery IS \'(DC2Type:encrypted_array)\'');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".organisation_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE document_file_update ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_update ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_update ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE document_file_update ALTER document_file_set_id TYPE UUID');
        $this->addSql('ALTER TABLE document_file_update ALTER document_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN document_file_update.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.document_file_set_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN document_file_update.document_id IS \'(DC2Type:uuid)\'');
    }
}
