parameters:
    publication_api_servers:
        - url: 'https://localhost:8443'
          description: 'Local development docker environment for tenant minvws'
        - url: 'https://localhost:8444'
          description: 'Local development docker environment for tenant minfin'
