name: Bug
description: Meld een bug.
projects: ["minvws/30"]
type: Bug
body:
  - type: textarea
    attributes:
      label: Reproductie stappen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Geobserveerd gedrag
    validations:
      required: true
  - type: textarea
    attributes:
      label: Verwacht gedrag
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Git branch kiezen
      options:
        - Maak een PR naar de huidige release branch (vX.X.X)
        - Maak een PR naar de main branch
    validations:
      required: true
