# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

app_contact:
    path:          /contact
    controller:    Shared\Controller\Public\ContentPageController::page
    defaults:
        slug: 'contact'
    options:
        sitemap:
          priority: 0.7
          changefreq: monthly

app_privacy:
    path:          /privacy
    controller:    Shared\Controller\Public\ContentPageController::page
    defaults:
        slug: 'privacy'
    options:
        sitemap:
          priority: 0.7
          changefreq: monthly
          section: legal

app_about:
    path:          /over-dit-platform
    controller:    Shared\Controller\Public\ContentPageController::page
    defaults:
        slug: 'over-dit-platform'
    options:
        sitemap:
          priority: 0.7
          changefreq: monthly
          section: legal

app_copyright:
    path:          /copyright
    controller:    Shared\Controller\Public\ContentPageController::page
    defaults:
        slug: 'copyright'
    options:
        sitemap:
          priority: 0.7
          changefreq: monthly
          section: legal

app_cookies:
    path:          /cookies
    controller:    Shared\Controller\Public\ContentPageController::page
    defaults:
        slug: 'cookies'
    options:
        sitemap:
            priority: 0.7
            changefreq: monthly
            section: legal

app_accessibility:
    path:          /toegankelijkheid
    controller:    Shared\Controller\Public\ContentPageController::page
    defaults:
        slug: 'toegankelijkheid'
    options:
        sitemap:
            priority: 0.7
            changefreq: monthly
            section: legal

app_report_vulnerability:
    path:          /kwetsbaarheid-melden
    controller:    Shared\Controller\Public\ContentPageController::page
    defaults:
        slug: 'kwetsbaarheid-melden'
    options:
        sitemap:
            priority: 0.7
            changefreq: monthly
            section: legal
