parameters:
    configPageLimit: '%env(int:DOCUMENT_PAGE_LIMIT)%'
    env(DOCUMENT_PAGE_LIMIT): '0'
    env(HAS_FEATURE_WOO_GPT): 'false'

    env(ENABLE_TOOLBAR) : 'true'
    enable_symfony_toolbar: '%env(bool:ENABLE_TOOLBAR)%'

    env(LIMIT_TOTAL_DOCUMENT_FILE_SIZE_IN_GIB): '50'
    limit_total_document_file_size_in_gib: '%env(int:LIMIT_TOTAL_DOCUMENT_FILE_SIZE_IN_GIB)%'

    available_locales: ['en', 'nl']
    app_mode: '%env(APP_MODE)%'
    thumbnail_limit: 50

    elasticsearch.suggestions_search_input: 'search-input'

imports:
    - { resource: services/default_autowire.yaml }
    - { resource: services/woo_index.yaml }
    - { resource: services/batch_archiver.yaml }
    - { resource: services/es_index.yaml }
    - { resource: services/decision_weights.php }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            Psr\Log\LoggerInterface $logger: '@Shared\Service\Logging\EnrichedPsrLogger'

    Shared\Service\Security\ApplicationMode\ApplicationMode:
        factory: ['Shared\Service\Security\ApplicationMode\ApplicationMode', 'fromEnvVar']
        arguments: [ '%app_mode%' ]

    Shared\ApplicationId:
        factory: ['@kernel', 'getApplicationId']

    Shared\Domain\Search\Index\Rollover\MappingService:
        arguments:
            $rootDir: '%kernel.project_dir%'

    Elastic\Elasticsearch\Client:
        factory: ['Shared\Service\Elastic\ElasticClientFactory', 'create']
        arguments:
            $host: '%elasticsearch.host%'
            $username: '%elasticsearch.user%'
            $password: '%elasticsearch.pass%'
            $mtlsCertPath: '%elasticsearch.mtls.cert_path%'
            $mtlsKeyPath: '%elasticsearch.mtls.key_path%'
            $mtlsCAPath: '%elasticsearch.mtls.ca_path%'

    Elastic\Elasticsearch\ClientInterface:
        alias: 'Shared\DataCollector\CollectorClient'

    tika.client:
        class: GuzzleHttp\Client
        factory: ['Shared\Domain\Ingest\Content\Extractor\Tika\TikaGuzzleClientFactory', 'create']
        arguments:
            $tikaHost: '%env(TIKA_HOST)%'

    Shared\Domain\Ingest\Content\Extractor\Tika\TikaService:
        $client: '@tika.client'

    Shared\Service\Inventory\Reader\InventoryReaderFactory:
        arguments:
            $factories:
                - '@Shared\Service\FileReader\ExcelCsvReaderFactory'

    Shared\Service\Stats\WorkerStatsService:
        arguments:
            $handlers:
                - '@Shared\Service\Stats\Handler\ElasticHandler'
                - '@Shared\Service\Stats\Handler\DoctrineHandler'

    # Public is true, because we need to inject this service in the DBAL types (see /App/Doctrine/Encrypted*.php files)
    Shared\Service\Encryption\EncryptionService:
        public: true
        arguments:
            $encryptionKey: '%database_encryption_key%'

    Shared\Service\Encryption\EncryptionServiceInterface:
        alias: 'Shared\Service\Encryption\EncryptionService'
        public: true

    Shared\Service\Storage\EntityStorageService:
        arguments:
            $isLocal: "@=env('STORAGE_DOCUMENT_ADAPTER')=='local' ? true : false"
            $documentRoot: '%document_path%'

    Shared\Twig\Runtime\AppExtensionRuntime:
        arguments:
            $projectPath: '%kernel.project_dir%'

    Shared\Domain\Publication\BatchDownload\BatchDownloadStorage:
        arguments:
            $filesystem: '@batch.storage'

    Shared\EventSubscriber\LocaleListener:
        arguments:
            $defaultLocale: '%kernel.default_locale%'
            $allowedLocales: '%available_locales%'

    Shared\Service\Totp:
        arguments:
            $issuer: '%totp_issuer%'

    Shared\Command\CleanSheet:
        arguments:
            $queueDsns: [
                '%high_transport_dsn%',
                '%ingestor_transport_dsn%',
                '%esupdater_transport_dsn%',
                '%global_transport_dsn%',
            ]

    Shared\Controller\Public\StatsController:
        arguments:
            $redis: '@snc_redis.ingest'
            $rabbitMqStatUrl: '%rabbitmq_stats_url%'


    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            $redis: '@snc_redis.session'

    Shared\Service\Security\Session\EncryptedSessionProxy:
        arguments:
            - '@Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler'
            - '%app_secret%'

    Shared\Service\Logging\EnrichedPsrLogger:
        arguments:
            $logger: '@monolog.logger'

    Psr\Log\LoggerInterface:
        alias: 'Shared\Service\Logging\EnrichedPsrLogger'
        public: true

    Aws\S3\S3Client:
        arguments:
            - version: '2006-03-01'
              region: '%storage.minio.region%'
              endpoint: '%storage.minio.endpoint%'
              use_path_style_endpoint: true
              credentials:
                key: '%storage.minio.access_key%'
                secret: '%storage.minio.secret_key%'

    Shared\Service\Security\Authorization\AuthorizationMatrix:
        arguments:
            $entries: '@=service("Shared\\Service\\Security\\Authorization\\ConfigFactory").create()'

    Shared\Service\Security\Authorization\ConfigFactory:
        arguments:
            $config: '%authorization_matrix%'

    Shared\Service\Inventory\Sanitizer\InventorySanitizer:
        arguments:
            $writer: '@Shared\Service\Inventory\Sanitizer\ExcelWriter'

    Shared\Service\Inventory\Sanitizer\InventoryDocumentMapper:
        arguments:
            $publicBaseUrl: '%public_base_url%'

    Shared\Service\HistoryService:
        arguments:
            $translator: '@translator.default'

    Shared\Domain\Upload\Extractor\Extractor:
        public: true
        arguments:
            $archive: '@Shared\Domain\ArchiveExtractor\SevenZipArchive'

    Shared\Domain\Upload\AntiVirus\ClamAvClientFactory:
        arguments:
            $address: '%env(CLAM_AV_ADDRESS)%'

    Shared\Domain\Upload\AntiVirus\ClamAvFileScanner:
        arguments:
            $fileSizeLimit: '%env(CLAM_AV_MAX_FILESIZE)%'

    Shared\Domain\Upload\Handler\S3\S3UploadHelper:
        arguments:
            $bucket: '%storage.minio.bucket.upload%'

    League\MimeTypeDetection\FinfoMimeTypeDetector:
        arguments:
            $bufferSampleSize: !php/const Shared\Domain\Upload\FileType\MimeTypeHelper::SAMPLE_SIZE

    Shared\Domain\Robots\RobotsViewFactory:
        arguments:
            $publicBaseUrl: '%public_base_url%'

    Minvws\HorseBattery\HorseBattery: ~
    Minvws\HorseBattery\PasswordGenerator: '@Minvws\HorseBattery\HorseBattery'

when@dev:
    services: &services_dev
        Shared\Tests\Factory\:
            autowire: true
            autoconfigure: true
            resource: '../tests/Factory'

        Faker\Generator:
            public: true
            factory: ['Shared\Tests\Faker\FakerFactory', 'create']

        Shared\Tests\Story\:
            autowire: true
            autoconfigure: true
            resource: '../tests/Story'

when@test:
    services:
        <<: *services_dev

        markdown_converter.department:
            class: Shared\Domain\Content\Markdown\MarkdownConverter
            public: true

        # Alias for backward compatibility
        Shared\Domain\Department\Markdown\MarkdownConverter: '@markdown_converter.department'
