name: Setup PHP

inputs:
# Note: All inputs are cast to string. Even default values of type bool or int etc.
  php-version:
    description: The PHP version
    type:  string
    default: "8.3"
  coverage:
    description: Set PHP coverage driver
    type: string
    default: none
  extensions:
    description: Set PHP extensions
    type: string
  github-token:
    description: Add a Github Token which will be used for Composer auth
    type: string

runs:
  using: composite
  steps:
    - name: Get composer cache directory
      id: composer-cache-dir
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Restore Composer cache
      id: composer-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: ${{ inputs.coverage }}
        extensions: ${{ inputs.extensions }}
        github-token: ${{ inputs.github-token }}

    - name: Install dependencies
      shell: bash
      run: composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs

    - name: Copy .env.ci to .env.local
      shell: bash
      run: cp .env.ci .env.test.local

    - name: Save Composer cache
      if: ${{ always() && steps.composer-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
