parameters:
    app_secret: '%env(MINBUZA_APP_SECRET)%'
    public_base_url: '%env(MINBUZA_PUBLIC_BASE_URL)%'
    site_name: '%env(MINBUZA_SITE_NAME)%'
    cookie_name: '%env(MINBUZA_COOKIE_NAME)%'
    totp_issuer: '%env(MINBUZA_TOTP_ISSUER)%'
    trusted_hosts: '%env(MINBUZA_TRUSTED_HOSTS)%'
    database_encryption_key: '%env(MINBUZA_DATABASE_ENCRYPTION_KEY)%'

    # Elasticsearch
    elasticsearch.host: '%env(MINBUZA_ELASTICSEARCH_HOST)%'
    elasticsearch.user: '%env(MINBUZA_ELASTICSEARCH_USER)%'
    elasticsearch.pass: '%env(MINBUZA_ELASTICSEARCH_PASS)%'
    elasticsearch.mtls.cert_path: '%env(MINBUZA_ELASTICSEARCH_MTLS_CERT_PATH)%'
    elasticsearch.mtls.key_path: '%env(MINBUZA_ELASTICSEARCH_MTLS_KEY_PATH)%'
    elasticsearch.mtls.ca_path: '%env(MINBUZA_ELASTICSEARCH_MTLS_CA_PATH)%'

    # ElasticSearch indexes
    elasticsearch.index.prefix.default: 'minbuza-'
    elasticsearch.index.prefix: '%env(default:elasticsearch.index.prefix.default:MINBUZA_ELASTICSEARCH_INDEX_PREFIX)%'
    elasticsearch.index.read: '%elasticsearch.index.prefix%read'
    elasticsearch.index.write: '%elasticsearch.index.prefix%write'
    elasticsearch.index.worker_stats: '%elasticsearch.index.prefix%worker-stats'

    # RabbitMQ
    rabbitmq_url: '%env(MINBUZA_RABBITMQ_URL)%'
    rabbitmq_stats_url: '%env(MINBUZA_RABBITMQ_STATS_URL)%'

    high_transport_dsn: '%env(MINBUZA_HIGH_TRANSPORT_DSN)%'
    ingestor_transport_dsn: '%env(MINBUZA_INGESTOR_TRANSPORT_DSN)%'
    esupdater_transport_dsn: '%env(MINBUZA_ESUPDATER_TRANSPORT_DSN)%'
    global_transport_dsn: '%env(MINBUZA_GLOBAL_TRANSPORT_DSN)%'
    api_documents_transport_dsn: '%env(MINBUZA_API_DOCUMENTS_TRANSPORT_DSN)%'

    # Minio
    storage.minio.region: '%env(MINBUZA_STORAGE_MINIO_REGION)%'
    storage.minio.endpoint: '%env(MINBUZA_STORAGE_MINIO_ENDPOINT)%'
    storage.minio.access_key: '%env(MINBUZA_STORAGE_MINIO_ACCESS_KEY)%'
    storage.minio.secret_key: '%env(MINBUZA_STORAGE_MINIO_SECRET_KEY)%'

    storage.minio.bucket.upload: '%env(MINBUZA_STORAGE_MINIO_UPLOAD_BUCKET)%'
    storage.minio.bucket.document: '%env(MINBUZA_STORAGE_MINIO_DOCUMENT_BUCKET)%'
    storage.minio.bucket.batch: '%env(MINBUZA_STORAGE_MINIO_BATCH_BUCKET)%'
    storage.minio.bucket.woo_index: '%env(MINBUZA_STORAGE_MINIO_WOO_INDEX_BUCKET)%'
    storage.minio.bucket.assets: '%env(MINBUZA_STORAGE_MINIO_ASSETS_BUCKET)%'

    # Redis
    redis.url: '%env(MINBUZA_REDIS_URL)%'
    redis.tls.cafile: '%env(MINBUZA_REDIS_TLS_CAFILE)%'
    redis.tls.local_cert: '%env(MINBUZA_REDIS_TLS_LOCAL_CERT)%'
    redis.tls.local_pk: '%env(MINBUZA_REDIS_TLS_LOCAL_PK)%'

    # Application publication_api specific configs:
    publication_api_ssl_username_whitelist: '%env(string:MINBUZA_PUBLICATION_API_SSL_USERNAME_WHITELIST)%'
    publication_api_ssl_organization_identifier: '%env(string:MINBUZA_PUBLICATION_API_SSL_ORGANIZATION_IDENTIFIER)%'
