SetEnv APP_MODE BALIE
SetEnv APP_ID admin

DocumentRoot /var/www/html/public
DirectoryIndex /index.php

<Directory /var/www/html/public>
    AllowOverride All
    Require all granted

    FallbackResource /index.php
</Directory>
