SetEnv APP_MODE FRONTEND
SetEnv APP_ID public

DocumentRoot /var/www/html/public
DirectoryIndex /index.php

<Directory /var/www/html/public/documentatie>
    AllowOverride All
    Require all granted

    DirectoryIndex index.html
</Directory>

<Directory /var/www/html/public/api>
    AllowOverride All
    Require all granted

    DirectoryIndex index.html
</Directory>

<Directory /var/www/html/public>
    AllowOverride All
    Require all granted

    FallbackResource /index.php
</Directory>
