parameters:
    env(HAS_FEATURE_PUBLICATION_V1_API): false
    has_feature_publication_v1_api: '%env(bool:HAS_FEATURE_PUBLICATION_V1_API)%'
    env(ENABLE_UPDATE_PUBLISHED_DOSSIER_VIA_API): false
    enable_update_published_dossier_via_api: '%env(bool:ENABLE_UPDATE_PUBLISHED_DOSSIER_VIA_API)%'

imports:
    - { resource: services/api_servers.yaml }
    - { resource: services/default_autowire.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
