name: E2E Tests - Acceptance
on:
    schedule:
      - cron: '0 0 * * *' # This cron schedule runs the workflow every day at midnight UTC
    workflow_dispatch:

jobs:
  e2e-robot-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/robot_framework/requirements.txt --use-deprecated=legacy-resolver
        rfbrowser init
    - name: Execute Robot Framework tests
      env:
        OTP_SECRET_WOO: ${{ secrets.OTP_SECRET_WOO }}
        USERNAME_WOO_STAGING: ${{ secrets.USERNAME_WOO_STAGING }}
        PASSWORD_WOO_STAGING: ${{ secrets.PASSWORD_WOO_STAGING }}
      run: |
        python -m robot -d tests/robot_framework/results -x outputxunit.xml -i E2E_ACC -e LOGS -v headless:true tests/robot_framework
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: reports
        path: tests/robot_framework/results
    - name: Publish test results
      uses: minvws/nl-rdo-github-action-robotframework-test-summary@v0.2.0
      if: always()
      with:
        output_file: 'tests/robot_framework/results/output.xml'
        endpoints: 'https://web.acc.woo.rdobeheer.nl'
        username: '${{ secrets.USERNAME_WOO_STAGING }}'
        password: '${{ secrets.PASSWORD_WOO_STAGING }}'
