name: Limits

on:
  schedule:
    - cron:  0 0 * * 0  # “At 00:00 on Sunday.”


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20
  PHP_VERSION: 8.3
  GH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

jobs:
  test-ci:
    name: 'Run weekly test suite in CI'
    uses: minvws/nl-rdo-woo-web-private/.github/workflows/e2e-ci.yml@woo-5095-limits
    secrets: inherit
    with:
      test_tag: 'limits'
      runner: 'ubuntu-latest-m'
